# 应用名称
spring:
  application:
    name: springsecurity
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.81.66:3306/pangpan
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
